# Hexo Configuration
## Docs: https://mayanming696.github.io
## Source: https://mayanming696.github.io
# Site
title: Mayanming
subtitle: Mayanming
description: 个人博客
keywords: "Web前端"
author: Marco
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'https://mayanming696.com' and root as '/child/'
url: https://mayanming696.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
# gitalk
gitalk:
enable: true
owner: mayanming696
repo: mayanming696.github.io
oauth:
    clientId: a2fe0066079fb61004dd
    clientSecret: f15ff057b9513c8a177f04a7509b670a67681149
admin: mayanming696
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
  custom_css:

search:
  path: search.xml
  field: post

permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## https://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Extensions
## Plugins: https://mayanming696.github.io
## Themes: https://mayanming696.github.io
theme: matery

# Deployment
## Docs: https://mayanming696.github.io
deploy:
- type: git
  repo:
    github: git@github.com:mayanming696/mayanming696.github.io.git,master
    coding: git@git.dev.tencent.com:mayanming696/mayanming696.coding.me.git,master
- type: baidu_url_submitter


baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: mayanming696.com # 在百度站长平台中注册的域名
  token: GNngradAteMKeHp7 # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里



live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-shizuku
  display:
    position: left
    width: 200
    height: 400
  mobile:
    show: false
  react:
    opacity: 0.7


backup:
  type: git
  theme: matery
  message: 备份博客
  repository: 
      coding: git@git.coding.net:mayanming696/mayanming696.coding.me.git,hexo